/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Database.Avatar;
import Database.Cards;
import Database.Enemies;
import Manager.Deck_Manager;
import Manager.Level_Manager;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eron Asia
 */
public class BattlePanel extends javax.swing.JPanel {
    private GameFrame parent;
    private Level_Manager lvlManager;
    
    private ArrayList<Cards> onHand = new ArrayList<>();
    
    private float currHealth, currMana, currShield;
    /**
     * Creates new form BattlePanel
     */
    public BattlePanel() {
        this.setSize(new Dimension(1280,720));
        initComponents();
    }
    public BattlePanel(Level_Manager lvlManager){
        this.setSize(new Dimension(1280,720));
        this.lvlManager = lvlManager;
        initComponents();
        startGame();
    }
    private void startGame(){
        Deck_Manager AvatarDeck = this.lvlManager.getAvatar().getManager();
        ArrayList<Cards> deck = AvatarDeck.getDeck();
        Random rnd = new Random();
        
        Avatar character = this.lvlManager.getAvatar().getCharaceter();
        currHealth = character.getHealth();
        currMana = character.getMana();
        currShield = character.getShield();
        
        this.onHand.add(deck.get(rnd.nextInt(deck.size())));
        this.onHand.add(deck.get(rnd.nextInt(deck.size())));
        this.onHand.add(deck.get(rnd.nextInt(deck.size())));
        //Set Cards
        btnCard1.setIcon(this.onHand.get(0).getIcon());
        btnCard2.setIcon(this.onHand.get(1).getIcon());
        btnCard3.setIcon(this.onHand.get(2).getIcon());
        //Set Character
        lblCharacter1.setIcon(character.getImage());
        lblCharacter1.setText("");
        
        lblHealth.setText(Float.toString(currHealth) + " / "+ Float.toString(character.getHealth()));
        lblMana.setText(Float.toString(currMana)+" / "+Float.toString(character.getMana()));
        lblShield.setText(Float.toString(currShield)+" / "+Float.toString(character.getShield()));
        //Set Enemies
        
    }
    private boolean Restrict(){
        return onHand.size() > 3;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHealth = new javax.swing.JLabel();
        lblMana = new javax.swing.JLabel();
        lblShield = new javax.swing.JLabel();
        lblHealthIcon = new javax.swing.JLabel();
        lblShieldIcon = new javax.swing.JLabel();
        lblManaIcon = new javax.swing.JLabel();
        btnSkipTurn = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        btnCard1 = new javax.swing.JButton();
        lblEnemy = new javax.swing.JLabel();
        lblCharacter1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1240, 730));
        setPreferredSize(new java.awt.Dimension(1240, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHealth.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHealth.setForeground(new java.awt.Color(255, 255, 255));
        lblHealth.setText("HealthIndicator");
        add(lblHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 180, 50));

        lblMana.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMana.setForeground(new java.awt.Color(255, 255, 255));
        lblMana.setText("ManaIndicator");
        add(lblMana, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 190, 60));

        lblShield.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblShield.setForeground(new java.awt.Color(255, 255, 255));
        lblShield.setText("ShieldIndicator");
        lblShield.setPreferredSize(new java.awt.Dimension(82, 16));
        add(lblShield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 190, 50));

        lblHealthIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Health.png"))); // NOI18N
        add(lblHealthIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 40));

        lblShieldIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shield.png"))); // NOI18N
        add(lblShieldIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 50, 40));

        lblManaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mana.png"))); // NOI18N
        add(lblManaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 50, 40));

        btnSkipTurn.setText("Skip Turn");
        btnSkipTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipTurnActionPerformed(evt);
            }
        });
        add(btnSkipTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, 130, 50));

        btnCard2.setPreferredSize(new java.awt.Dimension(201, 256));
        btnCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard2ActionPerformed(evt);
            }
        });
        add(btnCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        btnCard3.setPreferredSize(new java.awt.Dimension(201, 256));
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });
        add(btnCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        btnCard1.setPreferredSize(new java.awt.Dimension(201, 256));
        btnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard1ActionPerformed(evt);
            }
        });
        add(btnCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        lblEnemy.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnemy.setForeground(new java.awt.Color(255, 255, 255));
        lblEnemy.setText("Enemy");
        add(lblEnemy, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 200, -1, -1));

        lblCharacter1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCharacter1.setForeground(new java.awt.Color(255, 255, 255));
        lblCharacter1.setText("Character");
        add(lblCharacter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FightSceneBg.png"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard1ActionPerformed

    private void btnCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard2ActionPerformed

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard3ActionPerformed

    private void btnSkipTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipTurnActionPerformed
        
    }//GEN-LAST:event_btnSkipTurnActionPerformed
    public static void main(String[] args){
        JFrame frame = new JFrame();
        frame.setSize(1280, 720);
        BattlePanel obj = new BattlePanel();
        frame.add(obj);
        frame.setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnSkipTurn;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCharacter1;
    private javax.swing.JLabel lblEnemy;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealthIcon;
    private javax.swing.JLabel lblMana;
    private javax.swing.JLabel lblManaIcon;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblShieldIcon;
    // End of variables declaration//GEN-END:variables
}
