/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;

import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author acer
 */
public class Map1 extends javax.swing.JPanel {

        private Image backgroundImage;
        private GameFrame parentFrame;
    public Map1() {
        this.setSize(new Dimension(1280,720));
        initComponents();
        initBG();
    } 
    
    
    public void initBG(){
        try {
            URL imageURL = getClass().getResource("/images/background.png");
            if (imageURL != null) {
                System.out.println("Image loaded successfully: " + imageURL.toString());
                backgroundImage = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("Image not found in resources.");
            }
        } catch (Exception e) {
            System.err.println("Error loading background image: " + e.getMessage());
        }
    }
    
    private void intoFight(){
        parentFrame = (GameFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.changePanel(new BattlePanel(parentFrame.getLvlManager()));
    }
    private void intoShop(){
        parentFrame = (GameFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.changePanel(new ShopScene());
    }
    private void intoRest(){
        parentFrame = (GameFrame) SwingUtilities.getWindowAncestor(this);
        parentFrame.changePanel(new RestingScene(parentFrame.getLvlManager()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param args
     */
        public void setOccIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OccurenceEvent.png")));
            this.intoShop();
        }
    
        public void setBattleIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy.gif")));
            this.intoFight();
        }
        
        public void setRestIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rest.gif")));
            this.intoRest();
        }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startPoint1 = new javax.swing.JButton();
        restM1 = new javax.swing.JButton();
        Rare_Occ2 = new javax.swing.JButton();
        fightp1 = new javax.swing.JButton();
        fightp2 = new javax.swing.JButton();
        FIght_MidBoss = new javax.swing.JButton();
        Rare_Occ1 = new javax.swing.JButton();
        fightp4 = new javax.swing.JButton();
        fightp3 = new javax.swing.JButton();
        restp1 = new javax.swing.JButton();
        fightp5 = new javax.swing.JButton();
        fightp6 = new javax.swing.JButton();
        fightp8 = new javax.swing.JButton();
        fightp7 = new javax.swing.JButton();
        restp2 = new javax.swing.JButton();
        Rare_Occ3 = new javax.swing.JButton();
        Finale = new javax.swing.JButton();
        fightp9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setMaximumSize(new java.awt.Dimension(640, 365));
        setMinimumSize(new java.awt.Dimension(640, 365));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPoint1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Attack.png"))); // NOI18N
        startPoint1.setBorder(null);
        startPoint1.setBorderPainted(false);
        startPoint1.setContentAreaFilled(false);
        add(startPoint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        startPoint1.getAccessibleContext().setAccessibleDescription("");

        restM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        restM1.setBorder(null);
        restM1.setBorderPainted(false);
        restM1.setContentAreaFilled(false);
        restM1.setMaximumSize(new java.awt.Dimension(34, 10));
        restM1.setMinimumSize(new java.awt.Dimension(34, 10));
        restM1.setPreferredSize(new java.awt.Dimension(34, 10));
        restM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restM1ActionPerformed(evt);
            }
        });
        add(restM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 35, 35));

        Rare_Occ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        Rare_Occ2.setBorder(null);
        Rare_Occ2.setBorderPainted(false);
        Rare_Occ2.setContentAreaFilled(false);
        Rare_Occ2.setMaximumSize(new java.awt.Dimension(34, 10));
        Rare_Occ2.setMinimumSize(new java.awt.Dimension(34, 10));
        Rare_Occ2.setPreferredSize(new java.awt.Dimension(34, 10));
        Rare_Occ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rare_Occ2ActionPerformed(evt);
            }
        });
        add(Rare_Occ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 35, 35));

        fightp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp1.setBorder(null);
        fightp1.setBorderPainted(false);
        fightp1.setContentAreaFilled(false);
        fightp1.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp1.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp1.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp1ActionPerformed(evt);
            }
        });
        add(fightp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 35, 35));

        fightp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp2.setBorder(null);
        fightp2.setBorderPainted(false);
        fightp2.setContentAreaFilled(false);
        fightp2.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp2.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp2.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp2ActionPerformed(evt);
            }
        });
        add(fightp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 35, 35));

        FIght_MidBoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        FIght_MidBoss.setBorder(null);
        FIght_MidBoss.setBorderPainted(false);
        FIght_MidBoss.setContentAreaFilled(false);
        FIght_MidBoss.setMaximumSize(new java.awt.Dimension(34, 10));
        FIght_MidBoss.setMinimumSize(new java.awt.Dimension(34, 10));
        FIght_MidBoss.setPreferredSize(new java.awt.Dimension(34, 10));
        FIght_MidBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIght_MidBossActionPerformed(evt);
            }
        });
        add(FIght_MidBoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 35, 35));

        Rare_Occ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        Rare_Occ1.setBorder(null);
        Rare_Occ1.setBorderPainted(false);
        Rare_Occ1.setContentAreaFilled(false);
        Rare_Occ1.setMaximumSize(new java.awt.Dimension(34, 10));
        Rare_Occ1.setMinimumSize(new java.awt.Dimension(34, 10));
        Rare_Occ1.setPreferredSize(new java.awt.Dimension(34, 10));
        Rare_Occ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rare_Occ1ActionPerformed(evt);
            }
        });
        add(Rare_Occ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 35, 35));

        fightp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp4.setBorder(null);
        fightp4.setContentAreaFilled(false);
        fightp4.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp4.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp4.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp4ActionPerformed(evt);
            }
        });
        add(fightp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 35, 35));

        fightp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp3.setBorder(null);
        fightp3.setBorderPainted(false);
        fightp3.setContentAreaFilled(false);
        fightp3.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp3.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp3.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp3ActionPerformed(evt);
            }
        });
        add(fightp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 35, 35));

        restp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        restp1.setBorder(null);
        restp1.setBorderPainted(false);
        restp1.setContentAreaFilled(false);
        restp1.setMaximumSize(new java.awt.Dimension(34, 10));
        restp1.setMinimumSize(new java.awt.Dimension(34, 10));
        restp1.setPreferredSize(new java.awt.Dimension(34, 10));
        restp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restp1ActionPerformed(evt);
            }
        });
        add(restp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 35, 35));

        fightp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp5.setBorder(null);
        fightp5.setBorderPainted(false);
        fightp5.setContentAreaFilled(false);
        fightp5.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp5.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp5.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp5ActionPerformed(evt);
            }
        });
        add(fightp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 35, 35));

        fightp6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp6.setBorder(null);
        fightp6.setBorderPainted(false);
        fightp6.setContentAreaFilled(false);
        fightp6.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp6.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp6.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp6ActionPerformed(evt);
            }
        });
        add(fightp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 520, 35, 35));

        fightp8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp8.setBorder(null);
        fightp8.setBorderPainted(false);
        fightp8.setContentAreaFilled(false);
        fightp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp8ActionPerformed(evt);
            }
        });
        add(fightp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 35, 35));

        fightp7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp7.setBorder(null);
        fightp7.setBorderPainted(false);
        fightp7.setContentAreaFilled(false);
        fightp7.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp7.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp7.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp7ActionPerformed(evt);
            }
        });
        add(fightp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 35, 35));

        restp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        restp2.setBorder(null);
        restp2.setBorderPainted(false);
        restp2.setContentAreaFilled(false);
        restp2.setMaximumSize(new java.awt.Dimension(34, 10));
        restp2.setMinimumSize(new java.awt.Dimension(34, 10));
        restp2.setPreferredSize(new java.awt.Dimension(34, 10));
        restp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restp2ActionPerformed(evt);
            }
        });
        add(restp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 35, 35));

        Rare_Occ3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        Rare_Occ3.setBorder(null);
        Rare_Occ3.setBorderPainted(false);
        Rare_Occ3.setContentAreaFilled(false);
        Rare_Occ3.setMaximumSize(new java.awt.Dimension(34, 10));
        Rare_Occ3.setMinimumSize(new java.awt.Dimension(34, 10));
        Rare_Occ3.setPreferredSize(new java.awt.Dimension(34, 10));
        Rare_Occ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rare_Occ3ActionPerformed(evt);
            }
        });
        add(Rare_Occ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 35, 35));

        Finale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boss.gif"))); // NOI18N
        Finale.setBorder(null);
        Finale.setBorderPainted(false);
        Finale.setContentAreaFilled(false);
        add(Finale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 56, 56));

        fightp9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UnknownP.png"))); // NOI18N
        fightp9.setBorder(null);
        fightp9.setBorderPainted(false);
        fightp9.setContentAreaFilled(false);
        fightp9.setMaximumSize(new java.awt.Dimension(34, 10));
        fightp9.setMinimumSize(new java.awt.Dimension(34, 10));
        fightp9.setPreferredSize(new java.awt.Dimension(34, 10));
        fightp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightp9ActionPerformed(evt);
            }
        });
        add(fightp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 35, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\GithubDesktop\\GIT_FinalProj\\GrailNRun\\GrainNRuin\\src\\main\\resources\\images\\legend (1).png")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 210, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\GithubDesktop\\GIT_FinalProj\\GrailNRun\\GrainNRuin\\src\\main\\resources\\images\\background.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void fightp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp1ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp1);
        
    }//GEN-LAST:event_fightp1ActionPerformed

    private void Rare_Occ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rare_Occ3ActionPerformed
        // TODO add your handling code here:
        setOccIcon(Rare_Occ3);
    }//GEN-LAST:event_Rare_Occ3ActionPerformed

    private void restM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restM1ActionPerformed
        // TODO add your handling code here:
        setRestIcon(restM1);
    }//GEN-LAST:event_restM1ActionPerformed

    private void fightp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp2ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp2);
        
    }//GEN-LAST:event_fightp2ActionPerformed

    private void Rare_Occ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rare_Occ2ActionPerformed
        // TODO add your handling code here:
        setOccIcon(Rare_Occ2);
        
    }//GEN-LAST:event_Rare_Occ2ActionPerformed

    private void Rare_Occ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rare_Occ1ActionPerformed
        // TODO add your handling code here:
        setOccIcon(Rare_Occ1);
        //Call method for Rare Occasion room
    }//GEN-LAST:event_Rare_Occ1ActionPerformed

    private void fightp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp3ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp3);
    }//GEN-LAST:event_fightp3ActionPerformed

    private void fightp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp8ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp8);
    }//GEN-LAST:event_fightp8ActionPerformed

    private void fightp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp5ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp5);
    }//GEN-LAST:event_fightp5ActionPerformed

    private void FIght_MidBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIght_MidBossActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FIght_MidBossActionPerformed

    private void fightp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp4ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp4);
    }//GEN-LAST:event_fightp4ActionPerformed

    private void restp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restp1ActionPerformed
        // TODO add your handling code here:
        setRestIcon(restp1);
    }//GEN-LAST:event_restp1ActionPerformed

    private void fightp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp6ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp6);
    }//GEN-LAST:event_fightp6ActionPerformed

    private void fightp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp7ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp7);
    }//GEN-LAST:event_fightp7ActionPerformed

    private void fightp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightp9ActionPerformed
        // TODO add your handling code here:
        setBattleIcon(fightp9);
    }//GEN-LAST:event_fightp9ActionPerformed

    private void restp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restp2ActionPerformed
        // TODO add your handling code here:
        setRestIcon(restp2);
    }//GEN-LAST:event_restp2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FIght_MidBoss;
    private javax.swing.JButton Finale;
    private javax.swing.JButton Rare_Occ1;
    private javax.swing.JButton Rare_Occ2;
    private javax.swing.JButton Rare_Occ3;
    private javax.swing.JButton fightp1;
    private javax.swing.JButton fightp2;
    private javax.swing.JButton fightp3;
    private javax.swing.JButton fightp4;
    private javax.swing.JButton fightp5;
    private javax.swing.JButton fightp6;
    private javax.swing.JButton fightp7;
    private javax.swing.JButton fightp8;
    private javax.swing.JButton fightp9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton restM1;
    private javax.swing.JButton restp1;
    private javax.swing.JButton restp2;
    private javax.swing.JButton startPoint1;
    // End of variables declaration//GEN-END:variables


}
