/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import Database.Cards;
import Database.Relics;
import Manager.Level_Manager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class Shop extends javax.swing.JPanel {
    private Level_Manager lvlManager = new Level_Manager();
    
    /**
     * Creates new form Shop
     */
    
    private Image backgroundImage;
    
    
    public Shop() {
        this.setSize(new Dimension(640,360));
        initComponents();
        initBG();
//        implement();
    }
    private void implement(){
        Relics relic = lvlManager.getRandomRelic();
        Cards card = lvlManager.getRandomCard();
        
        if(relic != null){
            System.out.println("relic Inserted");
        }
        if (card != null){
            System.out.println("card Inserted");
        }
        this.jCard.setText("");
        this.jRelic.setText("");
        this.jCard.setIcon(new ImageIcon(relic.getImg()));
        this.jRelic.setIcon(new ImageIcon(card.getImg()));
    }
    
    public void initBG(){
        try {
            URL imageURL = getClass().getResource("/images/shopBG.png");
            if (imageURL != null) {
                System.out.println("Image loaded successfully: " + imageURL.toString());
                backgroundImage = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("Image not found in resources.");
            }
        } catch (Exception e) {
            System.err.println("Error loading background image: " + e.getMessage());
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            if (backgroundImage != null) {
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            } else {
                g.setColor(Color.RED);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCard = new javax.swing.JButton();
        jRelic = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(640, 360));

        jCard.setIcon(new javax.swing.ImageIcon("G:\\GithubDesktop\\GIT_FinalProj\\GrailNRun\\GrainNRuin\\src\\main\\resources\\images\\cards\\Cataclysm.png")); // NOI18N
        jCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCardActionPerformed(evt);
            }
        });

        jRelic.setIcon(new javax.swing.ImageIcon("G:\\GithubDesktop\\GIT_FinalProj\\GrailNRun\\GrainNRuin\\src\\main\\resources\\images\\Agi&IntNecklace.png")); // NOI18N
        jRelic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jCard, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jRelic, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCard, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRelic, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCardActionPerformed
        System.out.println("Item Inserted");
    }//GEN-LAST:event_jCardActionPerformed

    private void jRelicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelicActionPerformed
        System.out.println("Item Inserted");
    }//GEN-LAST:event_jRelicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCard;
    private javax.swing.JButton jRelic;
    // End of variables declaration//GEN-END:variables
}
