/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class BattlePanel extends javax.swing.JPanel {

    /**
     * Creates new form BattlePanel
     */
    private Image backgroundImage;
    
    public BattlePanel() {
        
        initComponents();
        initBG();
    }
    
    public void initBG(){
        try {
            URL imageURL = getClass().getResource("/images/FightSceneBg.png");
            if (imageURL != null) {
                System.out.println("Image loaded successfully: " + imageURL.toString());
                backgroundImage = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("Image not found in resources.");
            }
        } catch (Exception e) {
            System.err.println("Error loading background image: " + e.getMessage());
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            if (backgroundImage != null) {
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            } else {
                g.setColor(Color.RED);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCard1 = new javax.swing.JButton();
        btnCard2 = new javax.swing.JButton();
        btnCard3 = new javax.swing.JButton();
        lblHealth = new javax.swing.JLabel();
        lblShield = new javax.swing.JLabel();
        lblMana = new javax.swing.JLabel();
        btnSkipTurn = new javax.swing.JButton();
        lblHealthIcon = new javax.swing.JLabel();
        lblShieldIcon = new javax.swing.JLabel();
        lblManaIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCharacter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCard1.setPreferredSize(new java.awt.Dimension(121, 154));
        btnCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard1ActionPerformed(evt);
            }
        });
        add(btnCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnCard2.setPreferredSize(new java.awt.Dimension(121, 154));
        btnCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard2ActionPerformed(evt);
            }
        });
        add(btnCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 192, -1, -1));

        btnCard3.setAutoscrolls(true);
        btnCard3.setPreferredSize(new java.awt.Dimension(121, 154));
        btnCard3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCard3ActionPerformed(evt);
            }
        });
        add(btnCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 192, -1, -1));

        lblHealth.setText("HealthIndicator");
        add(lblHealth, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 215, 71, -1));

        lblShield.setText("ShieldIndicator");
        add(lblShield, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 249, 70, -1));

        lblMana.setText("ManaIndicator");
        add(lblMana, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 283, 67, -1));

        btnSkipTurn.setText("Skip Turn");
        btnSkipTurn.setToolTipText("");
        btnSkipTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipTurnActionPerformed(evt);
            }
        });
        add(btnSkipTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 246, 100, -1));

        lblHealthIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Health.png"))); // NOI18N
        add(lblHealthIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 214, -1, -1));

        lblShieldIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shield.png"))); // NOI18N
        add(lblShieldIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, -1, -1));

        lblManaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mana.png"))); // NOI18N
        add(lblManaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 282, -1, -1));

        jLabel2.setText("enemy");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 130, -1));

        lblCharacter.setText("character");
        add(lblCharacter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FightSceneBg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkipTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSkipTurnActionPerformed

    private void btnCard3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard3ActionPerformed

    private void btnCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard2ActionPerformed

    private void btnCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCard1ActionPerformed

    public static void main(String[] args){
        JFrame frame = new JFrame();
        frame.setSize(640,360);
        BattlePanel obj = new BattlePanel();
        frame.add(obj);
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard1;
    private javax.swing.JButton btnCard2;
    private javax.swing.JButton btnCard3;
    private javax.swing.JButton btnSkipTurn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCharacter;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblHealthIcon;
    private javax.swing.JLabel lblMana;
    private javax.swing.JLabel lblManaIcon;
    private javax.swing.JLabel lblShield;
    private javax.swing.JLabel lblShieldIcon;
    // End of variables declaration//GEN-END:variables
}
