/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author acer
 */
public class Map2 extends javax.swing.JPanel {

    /**
     * Creates new form Map2
     */
    
    private Image backgroundImage;
    
    public Map2() {
        initComponents();
        initBG();
        
        
//        setLabelToAll();
    }
    
    public static void main(String[] args) {
            JFrame frame = new JFrame("Map Example");
            frame.setSize(300, 200);

            JPanel panel = new JPanel(new GridLayout(10, 5)); // 2 rows, 2 columns

            // Create buttons and add them to the panel
            JButton button1 = new JButton("Button 1");
            JButton button2 = new JButton("Button 2");
            JButton button3 = new JButton("Button 3");
            JButton button4 = new JButton("Button 4");

            panel.add(button1);
            panel.add(button2);
            panel.add(button3);
            panel.add(button4);

        frame.add(panel);
        frame.setVisible(true);
    }
    
    public void initBG(){
        try {
            URL imageURL = getClass().getResource("/images/background.png");
            if (imageURL != null) {
                System.out.println("Image loaded successfully: " + imageURL.toString());
                backgroundImage = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("Image not found in resources.");
            }
        } catch (Exception e) {
            System.err.println("Error loading background image: " + e.getMessage());
        }
    }
    
//    public void setLabelToAll(){
//        setLabelBounds(startPoint1);
//        setLabelBounds(restp2);
//        setLabelBounds(restp1);
//        setLabelBounds(restM1);
//        setLabelBounds(fightp9);
//        setLabelBounds(fightp8);
//        setLabelBounds(fightp7);
//        setLabelBounds(fightp6);
//        setLabelBounds(fightp5);
//        setLabelBounds(fightp4);
//        setLabelBounds(fightp3);
//        setLabelBounds(fightp2);
//        setLabelBounds(fightp1);
//        setLabelBounds(Rare_Occ3);
//        setLabelBounds(Rare_Occ2);
//        setLabelBounds(Rare_Occ1);
//        setLabelBounds(Finale);
//        setLabelBounds(FIght_MidBoss);
//    }
    
    private void setLabelBounds(JButton button) {
        JLabel label = new JLabel();
        label.setBounds(button.getBounds());
        add(label);
        setComponentZOrder(label, 1);
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            if (backgroundImage != null) {
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            } else {
                g.setColor(Color.RED);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
        public void setOccIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OccurenceEvent.png")));
        }
    
        public void setBattleIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enemy.gif")));
        }
        
        public void setRestIcon(JButton btn){
            btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rest.gif")));
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
