/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author acer
 */
public class Shop extends javax.swing.JPanel {

    /**
     * Creates new form Shop
     */
    
    private Image backgroundImage;
    
    
    public Shop() {
        initComponents();
        initBG();
        
//        goldCoins.setOpaque(true);
//        set this to true to make text background invisible

        
    }
    
    public void initBG(){
        try {
            URL imageURL = getClass().getResource("/images/shopBG.png");
            if (imageURL != null) {
                System.out.println("Image loaded successfully: " + imageURL.toString());
                backgroundImage = new ImageIcon(imageURL).getImage();
            } else {
                System.err.println("Image not found in resources.");
            }
        } catch (Exception e) {
            System.err.println("Error loading background image: " + e.getMessage());
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            if (backgroundImage != null) {
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            } else {
                g.setColor(Color.RED);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String[] args){
        JFrame frame = new JFrame();
        frame.setSize(640, 360);
        
        Shop shop = new Shop();
        
        frame.add(shop);
        
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Card = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGoldCoins = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        goldCoins = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 360));
        setLayout(null);

        Card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Card_Back.png"))); // NOI18N
        add(Card);
        Card.setBounds(140, 90, 121, 154);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Relic_Back.png"))); // NOI18N
        add(jButton1);
        jButton1.setBounds(350, 90, 121, 154);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(280, 20, 50, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coin.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(600, 20, 20, 20);
        add(txtGoldCoins);
        txtGoldCoins.setBounds(560, 20, 0, 0);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btnExit.setContentAreaFilled(false);
        add(btnExit);
        btnExit.setBounds(540, 270, 70, 30);

        goldCoins.setOpaque(true);
        add(goldCoins);
        goldCoins.setBounds(560, 20, 0, 0);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Card;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel goldCoins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtGoldCoins;
    // End of variables declaration//GEN-END:variables
}
